apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mixtral-8x7b-inference
  namespace: llm-models
spec:
  to:
    kind: Service
    name: mixtral-8x7b-predictor
  port:
    targetPort: mixtral-8x7b-predictor
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
